name:                rinha-compilador
version:             0.1.0.0
github:              "edusporto/rinha-compilador"
license:             BSD3
author:              "Eduardo Sandalo Porto"
maintainer:          "edu@sandalo.dev"
copyright:           "2023 Eduardo Sandalo Porto"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/edusporto/rinha-compilador>

dependencies:
- base >= 4.7 && < 5
- text
- aeson
- containers
- interpolate
- template-haskell

default-extensions:
- OverloadedStrings
- DeriveGeneric
- DeriveAnyClass
- LambdaCase
- TemplateHaskell
- MultiWayIf
- QuasiQuotes
- StandaloneDeriving

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  rinha-compilador-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rinha-compilador

tests:
  rinha-compilador-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - rinha-compilador
    - hunit
